// <auto-generated />
using APIhackaton.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIhackaton.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205190109_DniNoAutoincrement")]
    partial class DniNoAutoincrement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("APIhackaton.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("comision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dniDocente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("codigo");

                    b.HasIndex("dniDocente");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2025,
                            Turno = "Mañana",
                            codigo = "MAT01",
                            comision = 1,
                            dniDocente = 1001
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2025,
                            Turno = "Tarde",
                            codigo = "FIS01",
                            comision = 2,
                            dniDocente = 1002
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Materia", b =>
                {
                    b.Property<string>("codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("codigo");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            codigo = "MAT01",
                            nombre = "Matemáticas"
                        },
                        new
                        {
                            codigo = "FIS01",
                            nombre = "Física"
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Performance", b =>
                {
                    b.Property<int>("AlumnoDni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inasistencias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgresoGeneral")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Racha")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlumnoDni", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            AlumnoDni = 3001,
                            CursoId = 1,
                            Inasistencias = 2,
                            ProgresoGeneral = 70,
                            Racha = 3
                        },
                        new
                        {
                            AlumnoDni = 3002,
                            CursoId = 1,
                            Inasistencias = 0,
                            ProgresoGeneral = 85,
                            Racha = 5
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Persona", b =>
                {
                    b.Property<int>("dni")
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("dni");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("APIhackaton.Models.TutorAlumno", b =>
                {
                    b.Property<int>("AlumnoDni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TutorDni")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlumnoDni", "TutorDni");

                    b.HasIndex("TutorDni");

                    b.ToTable("TutoresAlumnos");

                    b.HasData(
                        new
                        {
                            AlumnoDni = 3001,
                            TutorDni = 2001
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Alumno", b =>
                {
                    b.HasBaseType("APIhackaton.Models.Persona");

                    b.ToTable("Alumnos", (string)null);

                    b.HasData(
                        new
                        {
                            dni = 3001,
                            apellido = "Lopez",
                            email = "juan@student.com",
                            estado = true,
                            nombre = "Juan",
                            rol = 1
                        },
                        new
                        {
                            dni = 3002,
                            apellido = "Garcia",
                            email = "maria@student.com",
                            estado = true,
                            nombre = "María",
                            rol = 1
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Docente", b =>
                {
                    b.HasBaseType("APIhackaton.Models.Persona");

                    b.ToTable("Docentes", (string)null);

                    b.HasData(
                        new
                        {
                            dni = 1001,
                            apellido = "Gomez",
                            email = "carlos@gymail.com",
                            estado = true,
                            nombre = "Carlos",
                            rol = 2
                        },
                        new
                        {
                            dni = 1002,
                            apellido = "Perez",
                            email = "ana@school.com",
                            estado = true,
                            nombre = "Ana",
                            rol = 2
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Tutor", b =>
                {
                    b.HasBaseType("APIhackaton.Models.Persona");

                    b.Property<int>("ContadorAlertas")
                        .HasColumnType("INTEGER");

                    b.ToTable("Tutores", (string)null);

                    b.HasData(
                        new
                        {
                            dni = 2001,
                            apellido = "Ruiz",
                            email = "laura@home.com",
                            estado = true,
                            nombre = "Laura",
                            rol = 3,
                            ContadorAlertas = 0
                        });
                });

            modelBuilder.Entity("APIhackaton.Models.Curso", b =>
                {
                    b.HasOne("APIhackaton.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIhackaton.Models.Docente", "Docente")
                        .WithMany("Cursos")
                        .HasForeignKey("dniDocente")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("APIhackaton.Models.Performance", b =>
                {
                    b.HasOne("APIhackaton.Models.Alumno", "Alumno")
                        .WithMany("Performances")
                        .HasForeignKey("AlumnoDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIhackaton.Models.Curso", "Curso")
                        .WithMany("Performances")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("APIhackaton.Models.TutorAlumno", b =>
                {
                    b.HasOne("APIhackaton.Models.Alumno", "Alumno")
                        .WithMany("TutorAlumnos")
                        .HasForeignKey("AlumnoDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIhackaton.Models.Tutor", "Tutor")
                        .WithMany("TutorAlumnos")
                        .HasForeignKey("TutorDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("APIhackaton.Models.Alumno", b =>
                {
                    b.HasOne("APIhackaton.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("APIhackaton.Models.Alumno", "dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIhackaton.Models.Docente", b =>
                {
                    b.HasOne("APIhackaton.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("APIhackaton.Models.Docente", "dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIhackaton.Models.Tutor", b =>
                {
                    b.HasOne("APIhackaton.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("APIhackaton.Models.Tutor", "dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIhackaton.Models.Curso", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("APIhackaton.Models.Alumno", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("TutorAlumnos");
                });

            modelBuilder.Entity("APIhackaton.Models.Docente", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("APIhackaton.Models.Tutor", b =>
                {
                    b.Navigation("TutorAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
