// <auto-generated />
using System;
using APIhackaton.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIhackaton.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205170655_UnifyPerformanceAndTutors")]
    partial class UnifyPerformanceAndTutors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("APIhackaton.Models.Alumno", b =>
                {
                    b.Property<int>("dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("dni");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("APIhackaton.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("comision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dniDocente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("APIhackaton.Models.Docente", b =>
                {
                    b.Property<int>("dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("dni");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("APIhackaton.Models.Materia", b =>
                {
                    b.Property<string>("codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("codigo");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("APIhackaton.Models.Performance", b =>
                {
                    b.Property<int>("AlumnoDni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inasistencias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgresoGeneral")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Racha")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlumnoDni", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("APIhackaton.Models.Tutor", b =>
                {
                    b.Property<int>("dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContadorAlertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("dni");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("APIhackaton.Models.TutorAlumno", b =>
                {
                    b.Property<int>("AlumnoDni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TutorDni")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlumnoDni", "TutorDni");

                    b.HasIndex("TutorDni");

                    b.ToTable("TutoresAlumnos");
                });

            modelBuilder.Entity("APIhackaton.Models.Alumno", b =>
                {
                    b.HasOne("APIhackaton.Models.Curso", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("APIhackaton.Models.Performance", b =>
                {
                    b.HasOne("APIhackaton.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIhackaton.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("APIhackaton.Models.TutorAlumno", b =>
                {
                    b.HasOne("APIhackaton.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIhackaton.Models.Tutor", "Tutor")
                        .WithMany("TutorAlumnos")
                        .HasForeignKey("TutorDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("APIhackaton.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("APIhackaton.Models.Tutor", b =>
                {
                    b.Navigation("TutorAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
